name: lanti_llm_image

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

# secrets:
#   # /run/secrets/huggingface_token
#   huggingface_token:
#     environment: "HUGGING_FACE_HUB_TOKEN"

volumes:
  comfyui_seedvr2:
  comfyui_user:
  # sd_models:
  # sd_repositories:

# https://docs.docker.com/compose/how-tos/gpu-support/
# https://docs.nvidia.com/ai-workbench/user-guide/latest/reference/projects/compose-reference.html#gpu-allocation-by-count
x-common-gpu: &common-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"

services:

  cache_python313:
    image: python:${VERSION_PYTHON313}
    profiles:
      - cache

  # stable_diffusion_webui:
  #   build:
  #     context: ./src/stable_diffusion_webui
  #     args:
  #       GID: ${GID}
  #       UID: ${UID}
  #       VERSION_DEBIAN: ${VERSION_DEBIAN}
  #   environment:
  #     - TZ=${TIMEZONE}
  #   secrets:
  #      - huggingface_token
  #   volumes:
  #     - ./outputs:/usr/src/webui/outputs
  #     - sd_models:/usr/src/webui/models
  #     - sd_repositories:/usr/src/webui/repositories
  #   ports:
  #     - 7860:7860
  #   <<: [ *common-gpu ]
  #   networks:
  #     - backend
  #   profiles:
  #     - a1111

  comfyui:
    build:
      context: ./src/comfyui
      args:
        COMFYUI_DIR: ${COMFYUI_DIR}
        VERSION_PYTHON: ${VERSION_PYTHON313}
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./models/checkpoints:${COMFYUI_DIR}/models/checkpoints:ro
      - ./models/clip_vision:${COMFYUI_DIR}/models/clip_vision:ro
      - ./models/controlnet:${COMFYUI_DIR}/models/controlnet:ro
      - ./models/diffusion_models:${COMFYUI_DIR}/models/diffusion_models:ro
      - ./models/text_encoders:${COMFYUI_DIR}/models/text_encoders:ro
      # - ./models/SEEDVR2:${COMFYUI_DIR}/models/SEEDVR2:rw
      - comfyui_seedvr2:${COMFYUI_DIR}/models/SEEDVR2
      - ./models/upscale_models:${COMFYUI_DIR}/models/upscale_models:ro
      - ./models/vae:${COMFYUI_DIR}/models/vae:ro
      - ./outputs:${COMFYUI_DIR}/output
      - comfyui_user:${COMFYUI_DIR}/user
    ports:
      - 8188:8188
    <<: [ *common-gpu ]
    networks:
      - backend
      - frontend
    profiles:
      - comfy
