name: lanti_llm_image

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

# secrets:
#   # /run/secrets/huggingface_token
#   huggingface_token:
#     environment: "HUGGING_FACE_HUB_TOKEN"

volumes:
  comfyui_user:
  # sd_models:
  # sd_repositories:

# https://docs.docker.com/compose/how-tos/gpu-support/
# https://docs.nvidia.com/ai-workbench/user-guide/latest/reference/projects/compose-reference.html#gpu-allocation-by-count
x-common-gpu: &common-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"

services:

  # cache_debian:
  #   image: debian:${VERSION_DEBIAN-latest}
  #   profiles:
  #     - cache
  # cache_ollama:
  #   image: ollama/ollama:${VERSION_OLLAMA-latest}
  #   profiles:
  #     - cache
  # cache_python312:
  #   image: python:${VERSION_PYTHON312}
  #   profiles:
  #     - cache

  cache_python312:
    image: python:${VERSION_PYTHON312}
    profiles:
      - cache
  cache_python313:
    image: python:${VERSION_PYTHON313}
    profiles:
      - cache

  # stable_diffusion_webui:
  #   build:
  #     context: ./src/stable_diffusion_webui
  #     args:
  #       GID: ${GID}
  #       UID: ${UID}
  #       VERSION_DEBIAN: ${VERSION_DEBIAN}
  #   environment:
  #     - TZ=${TIMEZONE}
  #   secrets:
  #      - huggingface_token
  #   volumes:
  #     - ./outputs:/usr/src/webui/outputs
  #     - sd_models:/usr/src/webui/models
  #     - sd_repositories:/usr/src/webui/repositories
  #   ports:
  #     - 7860:7860
  #   <<: [ *common-gpu ]
  #   networks:
  #     - backend
  #   profiles:
  #     - a1111

  comfyui:
    build:
      context: ./src/comfyui
      args:
        COMFYUI_DIR: ${COMFYUI_DIR}
        VERSION_PYTHON: ${VERSION_PYTHON312}
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./models/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors:${COMFYUI_DIR}/models/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors:ro
      - ./models/text_encoders/umt5_xxl_fp16.safetensors:${COMFYUI_DIR}/models/text_encoders/umt5_xxl_fp16.safetensors:ro
      - ./models/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors:${COMFYUI_DIR}/models/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors:ro
      - ./models/vae/wan_2.1_vae.safetensors:${COMFYUI_DIR}/models/vae/wan_2.1_vae.safetensors:ro
      - ./models/vae/wan2.2_vae.safetensors:${COMFYUI_DIR}/models/vae/wan2.2_vae.safetensors:ro
      - ./outputs:${COMFYUI_DIR}/output
      - comfyui_user:${COMFYUI_DIR}/user
    ports:
      - 8188:8188
    <<: [ *common-gpu ]
    networks:
      - backend
      - frontend
    profiles:
      - comfy
